# Generated by Django 5.2.4 on 2025-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('soil_moisture', models.IntegerField()),
                ('water_level', models.IntegerField()),
                ('irrigation_status', models.CharField(max_length=10)),
            ],
        ),
    ]
